server:
  port: 0

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
#    url: jdbc:h2:mem:test
    username: sa
    password:
  config:
    import:
      - classpath:/bootstrap.yml


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcom to the simple E-commerce

logging:
  level:
    com.example.userservice2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans
#token:
#  expiration_time: 86400000
#  secret: 6v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-Ev78q(*u$@h%)Sdk@%*df930-452J*I)@*$skdfst#(oeskejf13854ry@)*$#EU9