server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///home/seongjin/workspace/git-local-repo
          uri: https://github.com/seongjin-an/something-cloud-config
