server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/workspace/native-file-repo
        git:
#          uri: file:///home/seongjin/workspace/git-local-repo
          uri: https://github.com/seongjin-an/something-cloud-config
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
