server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/workspace/native-file-repo
        git:
#          uri: file:///home/seongjin/workspace/git-local-repo
          uri: https://github.com/seongjin-an/something-cloud-config
